name: CI

# Controls when the action will run.
on:
  push:
    branches:  '*'

  # Run for all pull requests
  pull_request:
    branches: '*'
    types: [opened]

env:
  CMAKE_DOXYGEN_INPUT_LIST: "Components Docs/src OgreMain PlugIns RenderSystems"
  OGRE_SOURCE_DIR: "./"
  OGRE_BINARY_DIR: "./"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Doxygen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Publish # Only on master branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_dir: ./
